# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8f78a6ef25795b83378c0b58011f0628c6af747dfaf95fe66abe583a57014c5ffa1764af456ecc18166ac70f35256381563b6ad5cd95d25acbd075b6c1e82fd

test:
  secret_key_base: 842607e1a1a3db3d5b0c767f08f4d24ad34d6e14f81ad4d353582cb80475f5a106ab46b05728686b82ce14125d152a0923408ba43a7366e1f2e35a298a4dce10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
